import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/Sidebar';

const geist = Geist({ subsets: ['latin'], variable: '--font-geist' });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geist.variable} font-sans`}>
                <div className="flex">
                    <Sidebar />
                    <main className="flex-1 min-h-screen ml-64 p-8">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}