import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/material/styles';
import { theme } from '@/theme';

const geist = Geist({ subsets: ['latin'], variable: '--font-geist' }); // Инициализация шрифта

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.variable} font-sans`}>
          <ThemeProvider theme={theme}>
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
